---

- name: ping the server # Give your task a name
  hosts: web               # Which computers from your inventory?
  tasks:                   # List of actions
  - name: ping the server 
  ansible.builtin.ping:

  